[package]
name = "rustor"
version = "0.1.0"
edition = "2021"

[dependencies]
aes-gcm = { version = "0.10.3", features = ["std"] }
anyhow = "1.0.86"
rand = "0.8.5"
sha2 = "0.10.8"
tokio = { version = "1.38.0", features = ["full"] }
x25519-dalek = "2.0.1"
